/*
 * This file is part of Bitrix Forum Reader.
 *
 * Copyright (C) 2016-2020 Alexander Kamyshnikov <axill777@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
*/
#ifndef __BFR_HTMLTAG_H__
#define __BFR_HTMLTAG_H__

#include "gumbo-parser/src/gumbo.h"

enum class HtmlTag {
	HTML = GUMBO_TAG_HTML,
	HEAD,
	TITLE,
	BASE,
	LINK,
	META,
	STYLE,
	SCRIPT,
	NOSCRIPT,
	TEMPLATE,
	BODY,
	ARTICLE,
	SECTION,
	NAV,
	ASIDE,
	H1,
	H2,
	H3,
	H4,
	H5,
	H6,
	HGROUP,
	HEADER,
	FOOTER,
	ADDRESS,
	P,
	HR,
	PRE,
	BLOCKQUOTE,
	OL,
	UL,
	LI,
	DL,
	DT,
	DD,
	FIGURE,
	FIGCAPTION,
	MAIN,
	DIV,
	A,
	EM,
	STRONG,
	SMALL,
	S,
	CITE,
	Q,
	DFN,
	ABBR,
	DATA,
	TIME,
	CODE,
	VAR,
	SAMP,
	KBD,
	SUB,
	SUP,
	I,
	B,
	U,
	MARK,
	RUBY,
	RT,
	RP,
	BDI,
	BDO,
	SPAN,
	BR,
	WBR,
	INS,
	DEL,
	IMAGE,
	IMG,
	IFRAME,
	EMBED,
	OBJECT,
	PARAM,
	VIDEO,
	AUDIO,
	SOURCE,
	TRACK,
	CANVAS,
	MAP,
	AREA,
	MATH,
	MI,
	MO,
	MN,
	MS,
	MTEXT,
	MGLYPH,
	MALIGNMARK,
	ANNOTATION_XML,
	SVG,
	FOREIGNOBJECT,
	DESC,
	TABLE,
	CAPTION,
	COLGROUP,
	COL,
	TBODY,
	THEAD,
	TFOOT,
	TR,
	TD,
	TH,
	FORM,
	FIELDSET,
	LEGEND,
	LABEL,
	INPUT,
	BUTTON,
	SELECT,
	DATALIST,
	OPTGROUP,
	OPTION,
	TEXTAREA,
	KEYGEN,
	OUTPUT,
	PROGRESS,
	METER,
	DETAILS,
	SUMMARY,
	MENU,
	MENUITEM,
	APPLET,
	ACRONYM,
	BGSOUND,
	DIR,
	FRAME,
	FRAMESET,
	NOFRAMES,
	ISINDEX,
	LISTING,
	XMP,
	NEXTID,
	NOEMBED,
	PLAINTEXT,
	RB,
	STRIKE,
	BASEFONT,
	BIG,
	BLINK,
	CENTER,
	FONT,
	MARQUEE,
	MULTICOL,
	NOBR,
	SPACER,
	TT,
	RTC,
	UNKNOWN,
	LAST,
};

static_assert(int(HtmlTag::LAST) == int(GUMBO_TAG_LAST),
	"HtmlTag should be identical with GUMBO_TAG, "
	"may be you use incompatible version of gumbo-parser");

#endif // __BFR_HTMLTAG_H__
